- platforms/android/build.gradle
It looks like VLC might be used to play a lot of the media in this app, but I haven't looked into it quite yet. Media playback might not work for the armv8 build because I think `libvlc` is only included for armv7 and x86 right now, but at least it builds on my phone for testing.
Since there are only separate builds for amazon and google to get IAP working, we can remove the amazon builds and get to work on removing all the code related to this next.
Most of my time tonight was spent trying to get the project to build in Android Studio, for some reason it only works using npx but hopefully once we start using newer libraries and tools that problem will solve itself.
> fix build for armv8 and remove amazon builds

- config.xml
- platforms/android/AndroidManifest.xml
- platforms/android/res/xml/config.xml
- platforms/android/src/acidhax/cordova/chromecast/Chromecast.java
- platforms/android/src/com/mb/android/media/MediaRes.java
- platforms/android/src/com/mb/android/media/MediaService.java
- platforms/android/src/com/mb/android/media/PlaybackService.java
- platforms/android/src/com/mb/android/media/RemotePlayerService.java
- platforms/android/src/com/mb/android/media/Strings.java
- platforms/android/src/com/mb/android/media/VideoPlayerActivity.java
- platforms/android/src/com/mb/android/media/VlcEventHandler.java
- platforms/android/src/com/mb/android/media/legacy/KitKatMediaService.java
- platforms/android/src/com/mb/android/webviews/MySystemWebViewClient.java
- platforms/android/src/org/jellyfin/mobile/MainActivity.java
Part of the continuing effort of rebranding from Emby to Jellyfin #3.
This changes the app ID used for Android (and iOS if we can get it working) to `org.jellyfin.mobile`.
> Update application ID

- src/cordova/vlcplayer.js
This is another step that will help us move the java into a plugin. We can temporarily ignore all the VLC related bindings and reimplement them later if we want.
> Disable vlcplayer on all builds temporarily

- docker-build.sh
Otherwise, it generates `jellyfin-android_debug_debug.apk`.
> Avoid double-debug in output APK file

- src/cordova/apphost.js
This should fix the layout being default to tv for some resolutions (tablets).
Since this app in meant to be run on android smartphones and tablets, its seems fit to assume the layout is of type mobile.
> default layout 'mobile' since this app is for android devices

- .gitmodules
- build
- config.xml
- package-lock.json
- package.json
This should fix issues when running npx cordova prepare.
Also i removed the submodule cordova-plugin-chromecast from the filesystem, in addition to including it directly using config.xml.
branch master was also added to .submodules for the submodule jellyfin-web.
package.json and config.xml are synced when cordova prepare run. So i found plugin spec compatible with npm and cordova, for nativeshell and the chromecast plugins.
> Optimize config.xml plugins spec

- CONTRIBUTORS.md
- src/cordova/apphost.js
In the current state of the jellyfin-web repo, the subtitle profiles defined in the android app don't work as expected. Since the android app uses a webview (very similar to running inside chrome) to render a web server, one can assume the subtitle profiles set in the jellyfin-web repo will also work with the android app. 
For instance, if the profile is set for a given subtitle format, that impacts on the deliveryMethod used for that subtitle. When omitting that format, assumes a different behavior, giving a workable deliveryMethod to the client.
This can be related to the fact that, recently the default html5 player replaced a dedicated player in jellyfin-web.
> Mirror subtitle profiles present in jellyfin-web to apphost.js 

- build
- build.yaml
**Changes**
Makes some minor modifications to better support the wrapping `jellyfin-build` infrastructure. Specifically:
1. Put the output in `../bin` rather than `../`, which is cleaner, and easier to grab from.
1. Add a `build.yaml` configuration listing the available package types. `build` within the repo doesn't use this (yet).
> Build improvements for wrapping infrastructure

- src/NativeShell/plugin.xml
- src/NativeShell/src/build.gradle
This PR should address the exception "java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion"
This exception is associated with the usage of a deprecated library https://github.com/mcxiaoke/android-volley
Since this library is used for the jellyfin-apiclient-java dependency, and updated for the most recent volley version available (abou 2 days ago), i updated the dependency for the master version in build.gradle of NativeShell.
I also removed the old dependency in plugin.xml of NativeShell.
This was tested with a emulator with API level 28 (Pie). I also used the changes made in #105, so partially i also tested those changes and they are working as intended.
> Fix exception "java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" for API level 28 and greater

- src/NativeShell/src/RemotePlayerService.java
added the playstate actions that android wear multimedia notification play/pause button sends to the list of accepted media buttons
> Fix android wear multimedia notification play/pause button not working

- src/NativeShell/src/RemotePlayerService.java
Adds a missing import statement in the NativeShell plugin which caused the build to fail.
> Add missing import

- package-lock.json
- package.json
- src/NativeShell/plugin.xml
This PR addresses the androidx support for the cordova project. To be able to use androidx with this project, we need to use the plugin https://github.com/dpa99c/cordova-plugin-androidx, following this thread in the cordova android github https://github.com/apache/cordova-android/issues/565. This plugin converts all android.support usages to their corresponding androix equivalent.
To use this plugin, we need at least version 9 of cordova, so i proceeded with the upgrade.
This PR needs the following PR to be approved to work properly: https://github.com/jellyfin/cordova-plugin-chromecast/pull/14
> Upgrade to androidx and cordova to latest

- README.md
This adds the missing --remote flag, in README, to fetch the most recent master version of jellyfin-web when building the app.
> Add --remote to fetch most recent master in README

- docker-build.sh
> Add completely foss flavor

- docker-build.sh
These should make running the container easier for someone. Defaults the build to debug and provides an error if an unknown `RELEASE` value is used.
Also:
* disable Cordova telemetry and thus telemetry prompt
* variable quoting
* split `mmv` command to two lines to make it easier to read in a narrow terminal (previously 154 chars wide)
> Docker enhancements

- .gitmodules
- README.md
- build
- gulpfile.js
- package-lock.json
- package.json
Removes the `jellyfin-web` submodule and installs from github using npm instead.
> Install jellyfin-web with npm

- docker-build.sh
This fixes an issue where the `prepare` script in `jellyfin-web` is not run due to it running as root in docker.
> Allow unsafe-perm when running npm in docker

- package-lock.json
- package.json
* Update jellyfin-web to latest master
* Updates jellyfin/cordova-plugin-chromecast to v0.1.1, which restores Chromecast for Android >7.1
> Update NPM packages used

- src/NativeShell/src/RemotePlayerService.java
Extension to #167 and #161. Without this merged, the app would resume playing a paused video on Bluetooth disconnect, which can be embarrassing at times as I learned today.
> If paused, do not resume on BT disconnect

- config.xml
should fix #220 with new web changes
> New release

- src/NativeShell/src/RemotePlayerService.java
This was causing artist and album to be swapped while using bluetooth. Not yet verified.
> Fix bluetooth music notification

- gulpfile.js
I confirmed this did not break live tv for me while it does remove the default poster.
> Remove csp rule for default video player poster

- package-lock.json
- package.json
Rollback web to the version used for the previous release since the build from master seems to be introducing several issues. The best I can tell, [this](https://github.com/jellyfin/jellyfin-web/commit/a612fdf87c0d692447abb3a0016c62bd81468c8f) is the last commit in web prior to the 0.9.7 release.
> Rollback web to version used for 0.9.7

- gulpfile.js
- package-lock.json
- package.json
Switched [`ublify-es`](https://www.npmjs.com/package/uglify-es) for [`terser`](https://github.com/terser/terser) because `uglify-es` is [no longer maintained](https://github.com/terser/terser#why-choose-terser)
> Switch uglify-es for terser

- src/NativeShell/www/apphost.js
Most likely it was valid when the app came bundled with libvlc, but it is valid no more.
The way it was handled by server was the following:
1. Okay, profile has no `VideoCodec`, assign `null` (JSON behaviour)
2. Okay, we found a matching container and a matching audio codec, and we interpret `null` as "any video codec"
3. Playback with black screen (only audio) happens
Looking through the history I see this profile in the very first version of jellyfin-android, so I think it was there to address the fact that libvlc (which was used in the early days) could have played any video codec. This is no longer true.
> Remove broken profile

- package.json
It contains a few important bugfixes, including playback resuming (instead of always starting from the beginning) and `.ASS` subtitles renderer fix.
Fixes https://github.com/jellyfin/jellyfin-android/issues/258
> Bump jf-web to 10.5.4

- README.md
Yes, there's already a "release" button, but now there's a mention of the available releases in the text. Closes https://github.com/jellyfin/jellyfin-android/issues/331
> Add mention of APKs available for download

- README.md
There is no development release type. Only production, libre and debug.
> Update Docker build instructions
