- app/src/main/res/values/strings.xml
`Enable the experimental ExoPlayer video player which supports more video formats and codecs is more integrated into the OS`
The part `is more integrated into the OS` seems like it's talking about the codecs (`and codecs is more integrated...`) which I think was not the intention and is also not grammatically correct (`codecs is`). I have added `, and` to make it clear what is being said.
> Improve wording of ExoPlayer setting.

- app/src/main/java/org/jellyfin/mobile/utils/ServerConnectionUtils.kt
Because connectivity will be checked using the fetchServerInfo function anyway.
Fixes #16
> Remove the "isReachable" check

- app/src/main/java/org/jellyfin/mobile/AppPreferences.kt
- app/src/main/java/org/jellyfin/mobile/settings/SettingsActivity.kt
Until there is full feature parity, ExoPlayer should not be enabled by default. Users can still enable it in the settings.
> Set ExoPlayer as disabled by default

- app/src/main/java/org/jellyfin/mobile/WebappActivity.kt
- app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt
Logging a CharSequence as a String in Timber causes a crash.
> Fix possible exception when logging errors

- app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt
- app/src/main/java/org/jellyfin/mobile/player/PlayerActivity.kt
- app/src/main/res/drawable/ic_info_white_24dp.xml
- app/src/main/res/drawable/playback_info_background.xml
- app/src/main/res/layout/activity_player.xml
- app/src/main/res/layout/exo_player_control_view.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
> Add basic playback info dialog

- app/build.gradle.kts
- buildSrc/src/main/kotlin/VersionUtils.kt
- settings.gradle.kts
See documented code and Kotlin Playground sample which includes a test: https://pl.kotl.in/O_ZNvkGbQ
> Add release candidate number to version code

- .ci/azure-pipelines.yml
- app/build.gradle.kts
- buildSrc/src/main/kotlin/VersionUtils.kt
All other builds will use version 0.0.0-dev.1 with version code 1.
Releasing the app is now as easy as tag and forget :)
Closes #37
> Use git tag as version for publishing

- app/src/main/java/org/jellyfin/mobile/MainActivity.kt
I think for now, this is the best solution to the problem. Injecting custom CSS is much more complicated, and even with the nowplayingbar moved up, there are still UI problems that'd need to be adressed.
Fix #69.
> Fix UI overlap by applying bottom insets

- app/src/main/assets/native/exoplayer.js
- app/src/main/assets/native/nativeshell.js
- app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
- app/src/main/java/org/jellyfin/mobile/bridge/NativePlayer.kt
- app/src/main/java/org/jellyfin/mobile/settings/SettingsActivity.kt
- app/src/main/res/values/strings.xml
No restart needed anymore. The plugin is now enabled by default and when item playback is requested we check if ExoPlayer is enabled or not.
Undoes #75 (Sorry @Maxr1998)
> Improve ExoPlayer enabling

- app/build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
The test setup was broken since the Kotlin 1.4 migration, this PR fixes that.
> Update kotest, rename JUnit dependency

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/jellyfin/mobile/AppPreferences.kt
- app/src/main/java/org/jellyfin/mobile/ApplicationModule.kt
- app/src/main/java/org/jellyfin/mobile/MainActivity.kt
- app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
- app/src/main/java/org/jellyfin/mobile/utils/PermissionRequestHelper.kt
- app/src/main/java/org/jellyfin/mobile/utils/SystemUtils.kt
- app/src/main/res/values/strings.xml
> Fix downloads not working below Android Q by properly requesting storage permissions

- app/src/main/java/org/jellyfin/mobile/MainActivity.kt
- app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt
In the future we should update the library to 1.3.0 and switch the JavaScript injection to WebMessageListener.
See https://developer.android.com/jetpack/androidx/releases/webkit
> Use WebViewClientCompat

- app/src/main/assets/index_patch.html
- app/src/main/java/org/jellyfin/mobile/MainActivity.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt
- app/src/main/java/org/jellyfin/mobile/webapp/ConnectionHelper.kt
I'm for some reason not really happy with this yet.. feedback is highly appreciated :innocent:
> Improve script injection for native bridge

- app/src/main/assets/native/externalplayer.js
- app/src/main/assets/native/nativeshell.js
- app/src/main/java/org/jellyfin/mobile/MainActivity.kt
- app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
- app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSource.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/res/values/strings.xml
Feel free to refactor the source code, the companion objects, Kotlin coroutines and english as well aren't my thing yet.
Supported players
- VLC Media Player
- MX Player
Notes
- Only works with DirectStream play method since a stream url is required.
- Uses ExoPlayer device profile since there is no way to get it from an external player.
> Implement external player feature

- app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt
- app/src/main/java/org/jellyfin/mobile/player/PlayerActivity.kt
- app/src/main/java/org/jellyfin/mobile/utils/UIExtensions.kt
- app/src/main/res/drawable/ic_screen_lock_white_24dp.xml
- app/src/main/res/drawable/ic_screen_unlock_white_24dp.xml
- app/src/main/res/drawable/playback_unlock_background.xml
- app/src/main/res/layout/activity_player.xml
- app/src/main/res/layout/exo_player_control_view.xml
> Add screen lock feature in ExoPlayer

- app/src/main/java/org/jellyfin/mobile/MainActivity.kt
And remove warning about unused 'v' parameter in build, missing for some reason in #74?
**Before**:
**After**:
> Fix UI overlap by applying also horizontal insets

- app/build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- settings.gradle.kts
The dependency substitution code is from the Android TV app. Note that it's not possible to use buildSrc inside of Gradle settings files.
**Testing**
To the if this actually fixes the issues you can enable ProGuard in the debug builds (copy the code from the release flavor in the build.gradle.kts file)
Closes #116 (tested) 
Closes #119 (tested)
> Fix ProGuard configuration

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/jellyfin/mobile/webapp/ConnectionHelper.kt
- app/src/main/res/layout/connect_server.xml
- app/src/main/res/values/strings.xml
Button only visible when at least one server is found
Closes #115 👀
> Implement auto discovery

- app/src/main/java/org/jellyfin/mobile/MainActivity.kt
- app/src/main/java/org/jellyfin/mobile/settings/SettingsActivity.kt
- app/src/main/java/org/jellyfin/mobile/utils/ApiExtensions.kt
- app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt
In the next order:
1. User settings
2. ~~Server settings~~
3. Android settings
For now, it's necessary to restart the application manually when the language is changed, as long as no [events](https://github.com/jellyfin/jellyfin-web/blob/c8b6b44b7bf79c5a14055c6262b85b5af9cd7554/src/scripts/globalize.js#L259) are handled.
Closes #83
> Use display language when available

- app/src/main/java/org/jellyfin/mobile/AppPreferences.kt
- app/src/main/java/org/jellyfin/mobile/player/PlayerActivity.kt
- app/src/main/java/org/jellyfin/mobile/settings/SettingsActivity.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/res/drawable/ic_brightness_white_24dp.xml
- app/src/main/res/drawable/ic_volume_white_24dp.xml
- app/src/main/res/layout/activity_player.xml
- app/src/main/res/layout/overlay_brightness_volume.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
> Added Native Player Gesture for Volume & Brightness 

- app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt
The webui needs the `appMode` property set to either `cordova` or `android` for some behavior. We didn't do that.
Relevant code in web: https://github.com/jellyfin/jellyfin-web/blob/692d404285c19e1700a74fec23b4804273d12ac3/src/components/castSenderApi.js#L3
As you can see, if the app mode is not set it will always load the cast_sender JavaScript from Google, this JS would then overwrite our own injected code. By setting the appMode it doesn't do that.
It doesn't fix most chromecast issues though.
> Set appMode for webui

- app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt
> Revert "Set appMode for webui"

- app/src/main/AndroidManifest.xml
- app/src/main/res/xml/network_security_config.xml
Closes #178
- https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html#Blog1:~:text=Trusting%20user%2Dadded%20CAs%20for%20all%20secure%20connections
- https://developer.android.com/training/articles/security-config#base-config:~:text=%3Ccertificates%20src%3D%22user%22%20%2F%3E
> Add Network Security Configuration file

- buildSrc/src/main/kotlin/Dependencies.kt
[Core-ktx Version 1.4.0-alpha01](https://developer.android.com/jetpack/androidx/releases/core#1.4.0-alpha01)
Relevant Bug Fixes
- Extracted v28+ calls into a separate static class, which fixes a NoClassDefFoundError error for View#OnUnhandledKeyEventListener when building an app bundle ([Id3419](https://android-review.googlesource.com/#/q/Id34194f77b9c7a2f0864e38d17ef6039733dee95))
See https://github.com/jellyfin/jellyfin-android/issues/172#issuecomment-706538410
> Update Core-ktx to 1.4.0-alpha01

- .ci/azure-pipelines.yml
As CarlosOlivo discovered in the #175 azure CI run throws a warning for a JDK error in JDK 1.8.
I looked up how to "update"/select which JDK gets used by the [`Gradle@2`](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=azure-devops) task and this basic PR is the result :wink: 
**Changes**
* update JDK version used by the `Gradle@2` tasks to JDK 11
**Issues**
* N/A
> chore(CI): update JavaVersion used by GradleW tasks

- app/src/main/java/org/jellyfin/mobile/fragment/ConnectFragment.kt
- app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
From https://developer.android.com/topic/libraries/view-binding#fragments
> Note: Fragments outlive their views. Make sure you clean up any references to the binding class instance in the fragment's onDestroyView() method.
> Handle fragment destroy properly to prevent leaks

- app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
This assumes that if an error occurs when loading the url of the saved instance, it is not available. Which would redirect the user to the connection fragment instead of showing a WebView error. Similar to previous behavior in v2.0.0-rc.3
Note: This only handles the case when even cache loading fails, #44 still needs to be fixed.
See https://github.com/jellyfin/jellyfin-android/issues/44#issuecomment-689607259 #131 #173
> Handle WebView error on unavailable instance

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/jellyfin/mobile/AppPreferences.kt
- app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
- app/src/main/java/org/jellyfin/mobile/settings/ExternalPlayerPackage.java
- app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/java/org/jellyfin/mobile/utils/SystemUtils.kt
- app/src/main/res/values/strings.xml
System choice by default.
Useful to force playback on a specific player without depending on android settings.
For now it only shows a list of the players that support playback tracking as long as they are installed and enabled.
> Add support for external player choice inside client settings

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/jellyfin/mobile/AppPreferences.kt
- app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
- app/src/main/java/org/jellyfin/mobile/media/MediaService.kt
- app/src/main/java/org/jellyfin/mobile/utils/ApiExtensions.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/automotive_app_desc.xml
- buildSrc/src/main/kotlin/Dependencies.kt
This change adds basic android auto support. A video of it in action for reference: https://youtu.be/Zl-ETVcv5BQ
Main changes:
- Implements a `MediaBrowserServiceCompat` which lets Android auto detect Jellyfin as a music player
- Supports library selection and drilling down into the library by different views (latest, albums, artists, songs, genres)
- Supports shuffling in the album view
- Supports prev / next tracks
- Shows thumbnails when possible
Notes:
- The `MediaService` (implementation of `MediaBrowserServiceCompat`) is a fairly standalone thing. Due to how android auto music players work, it will not rely on the main webview for ui. Instead it will use the `ApiClient` to load data from Jellyfin.
- Since it's a separate service and could/will launch independently from the main app, …
> Add android auto support

- buildSrc/src/main/kotlin/Dependencies.kt
[Activity-ktx Version 1.2.0-alpha01](https://developer.android.com/jetpack/androidx/releases/activity#1.2.0-alpha01)
Bug Fixes
- Fixed a regression introduced in Activity 1.1.0 when running on older versions of the platform where onBackPressed() would cause an IllegalStateException due to a bug in the android.app.FragmentManager. ([b/146290338](https://issuetracker.google.com/issues/146290338))
> Update Activity-ktx to 1.2.0-alpha01

- buildSrc/src/main/kotlin/Dependencies.kt
Closes #172
https://github.com/jellyfin/jellyfin-apiclient-java/releases/tag/v0.7.7
> Bump apiclient version to 0.7.7

- .ci/azure-pipelines.yml
Basically copied the current sign task to make it work with both libre and proprietary. Removed the `DeleteFiles` task since it never worked (although it should've worked, weird)
Will cherrypick to release branch after merge to master.
> Sign both proprietary and libre release apks

- buildSrc/src/main/kotlin/Dependencies.kt
@nielsvanvelzen: after approving, please let me rebase before merging!
> Dependency updates

- app/build.gradle.kts
- app/schemas/org.jellyfin.mobile.model.sql.JellyfinDatabase/2.json
- app/src/main/java/org/jellyfin/mobile/AppPreferences.kt
- app/src/main/java/org/jellyfin/mobile/ApplicationModule.kt
- app/src/main/java/org/jellyfin/mobile/MainActivity.kt
- app/src/main/java/org/jellyfin/mobile/controller/ServerController.kt
- app/src/main/java/org/jellyfin/mobile/fragment/ConnectFragment.kt
- app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
- app/src/main/java/org/jellyfin/mobile/media/MediaService.kt
- app/src/main/java/org/jellyfin/mobile/model/DatabaseModule.kt
- app/src/main/java/org/jellyfin/mobile/model/sql/JellyfinDatabase.kt
- app/src/main/java/org/jellyfin/mobile/model/sql/dao/ServerDao.kt
- app/src/main/java/org/jellyfin/mobile/model/sql/dao/UserDao.kt
- app/src/main/java/org/jellyfin/mobile/model/sql/entity/ServerEntity.kt
- app/src/main/java/org/jellyfin/mobile/model/sql/entity/ServerUser.kt
- app/src/main/java/org/jellyfin/mobile/model/sql/entity/UserEntity.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt
- app/src/main/java/org/jellyfin/mobile/viewmodel/MainViewModel.kt
- buildSrc/src/main/kotlin/Dependencies.kt
Got a bit bigger than I would've liked, but I had to change quite a few things to get this in. Also fixed some other things in the `MediaService` that I noticed. E.g. the `sendError()` would always crash the app in this form, as it's only used for custom commands within `MediaBrowserCompatService`. Instead, we just return a null result.
> Migrate server and user info to database

- .ci/azure-pipelines.yml
Not tested, probably doesn't work (see my comment on line 29)
> Fixes in setting JELLYFIN_VERSION

- buildSrc/src/main/kotlin/VersionUtils.kt
Each part of the semver should be able to use 2 digits. It didn't do that for PATCH.
Kotlin-playground test: https://pl.kotl.in/kwvS88jHC
> Fix version code calculation comment

- app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
> I did some testing and came to the conclusion that this issue only happens in the mobile android client because the actual issue is the webui not being able to serialize the name. I therefor think we should remove the normalization from the apiclient and add it to the android app only (at the part we send it to the JS code).
Here it is. Uses the regex from @CarlosOlivo (thanks!) and I can confirm it fixes the issue because I added a weird name to my emulator.
Closes jellyfin/jellyfin-apiclient-java#140
Closes jellyfin/jellyfin-apiclient-java#141
Closes #230
> Fix device name again

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/jellyfin/mobile/media/MediaExtensions.kt
- app/src/main/java/org/jellyfin/mobile/media/MediaNotificationManager.kt
- app/src/main/java/org/jellyfin/mobile/media/MediaService.kt
- app/src/main/java/org/jellyfin/mobile/media/car/LibraryBrowser.kt
- app/src/main/java/org/jellyfin/mobile/media/car/LibraryPage.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt
- app/src/main/res/values/strings.xml
- buildSrc/src/main/kotlin/Dependencies.kt
- Moves library browser code into extra class and package, as it will only be used for Android Auto.
- The loader function was split into multiple subfunctions and cleaned up.
- The format of 'parentIds' was improved, unexpected behaviour with queue selection fixed.
- Shuffling was temporarily removed and will be handled differently in the future.
- Also introduces preliminaries for casting and Android 11 seamless transfer, this isn't fully enabled yet however - it seems there are still some changes necessary within the AndroidX libraries.
Uses code from the android/uamp reference media player project: https://github.com/android/uamp
Closes #226.
> Improve and rework MediaService & Android Auto integration

- app/src/main/assets/native/nativeshell.js
Caused JSON parsing errors in 10.7 >= and thus playback not working
this condition literally never worked because it used an non-existing operator and property lol
> Fix bad device profile

- app/src/main/java/org/jellyfin/mobile/viewmodel/MainViewModel.kt
Prevents possible race conditions/crashes when using Android Auto simultaneously to the web client, caused by the server location change invalidating login credentials.
> Only change server location when different

- app/build.gradle.kts
Possible fix for F-Droid reproducible builds
> Disable PNG crunching for release variant as well

- app/build.gradle.kts
By enabling the ` vectorDrawables.useSupportLibrary` option the Android compiler will stop creating unnecessary png files.
> Fix build reproducibility

- app/src/main/assets/native-10.6/nativeshell.js
- app/src/main/assets/native-10.6/navigation.js
- app/src/main/assets/native-10.7/NavigationPlugin.js
- app/src/main/assets/native-10.7/nativeshell.js
- app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt
- app/src/main/java/org/jellyfin/mobile/webapp/RemoteVolumeProvider.kt
- app/src/main/java/org/jellyfin/mobile/webapp/WebappFunctionChannel.kt
Since the `require` function doesn't work anymore on 10.7, I migrated the inputManager calls to use playbackManager where possible, the back action uses the `appRouter` (`window.Emby.Page`) now. The updated code was tested and works both on 10.6 and 10.7.
> Fix webapp function calls

- app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt
Instead of only injecting when the main.bundle.js is requested, it attempts to inject for every *.bundle.js that is requested, and ensures one-time execution by setting a flag in window.
> Fix JS injection breaking on page reloads in 10.7

- app/src/main/assets/native-10.6/externalplayer.js
- app/src/main/assets/native-10.7/ExternalPlayerPlugin.js
Only allow intros, a single item to play and stop as there is no way to stop a playlist from an external player.
Closes #265
> Fix support for playlists in external player

- app/src/main/assets/native-10.7/chrome.cast.js
- app/src/main/assets/native-10.7/nativeshell.js
- app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/java/org/jellyfin/mobile/utils/WebAppUtils.kt
- Added a few logging statements
- Made the execCast and castCallback async so the JS engine will behave slightly different in the way everything is called
- This fixes the unstable client never loading
- Change how the chrome cast plugin is loaded to MITM the google url instead
- Because jellyfin-web does [some magic with that url](https://github.com/jellyfin/jellyfin-web/blob/eb1e501fad14b15ef3ea7d102c8caff46a4963ea/src/components/castSenderApi.js)
> Miscellaneous casting fixes

- app/src/main/java/org/jellyfin/mobile/player/PlayerFragment.kt
Fixes #174.
See: https://developer.android.com/training/system-ui/navigation
> When the user reopens the activity, onCreate() won't get called, so the system bars will remain visible. If you want system UI changes to persist as the user navigates in and out of your activity, set UI flags in onResume() or onWindowFocusChanged().
> Improve fullscreen, orientation and PiP handling

- .github/workflows/gradlew-update.yaml
- .github/workflows/gradlew-validate.yaml
- .github/workflows/merge-conflict-labeler.yaml
Part of this comes from jellyfin/jellyfin-apiclient-java#163 with some slight improvements, the labeler comes from the ATV repo with some changes (added a schedule).
> Add merge conflict labeler and gradle update and validate tasks

- app/src/main/java/org/jellyfin/mobile/MainActivity.kt
- app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/java/org/jellyfin/mobile/utils/WebViewUtils.kt
- app/src/main/res/values/strings.xml
- app/src/proprietary/java/org/jellyfin/mobile/cast/Chromecast.java
> Check WebView support and version

- app/src/main/assets/native/chrome.cast.js
I was investigating an issue I was having with casting ~(which has been fixed somewhere between the Playstore release and the tip of `master`)~ and found whenever the Chromecast js logged an error it was not stringified and thus would log `[object Object]`.
EDIT: Actually my issue is still present when using the gradle options to build, will raise an issue.
This PR addresses this by attempting to stringify the instance of `chrome.cast.Error`, if this fails or throws then the original behaviour will be used.
Before:
```
2021-03-21 01:25:37.543 7245-7245/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1444)] "Encountered cast error [object Object]", source: https://www.gstatic.com/cv/js/sender/v1/cast_sender.js (1444)
```
After:
```
2021-03-21 00:42:35.321 …
```
> Chromecast JS: Improve error logging.

- app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
I found during my last PR that all logs despite the level used in the JS layer would always go to the info level when logged in logcat.
This change simply overrides the `onConsoleMessage` method to log messages to the correct level.
This allows you to use the logcat filtering in IntelliJ/Android Studio to filter for logs normally and makes the messages less verbose.
The new messages are tagged with `WebView` and follow the original messages format, although happy to change any of this :)
Old:
```
2021-03-21 01:25:37.501 7245-7245/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "nowplaying event: init", source: http://192.168.0.100:8096/web/1372.2199cd4f8b32083a01bb.bundle.js (1)
2021-03-21 01:25:37.501 7245-7245/org.jellyfin.mobile.debug I/chromium: [INFO:CONSOLE(1)] "null", …
```
> WebView: Use timber for logging

- app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
- app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
- app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/java/org/jellyfin/mobile/utils/SystemUtils.kt
> Use Activity Result APIs for External player

- .ci/azure-pipelines.yml
- .github/workflows/app-test.yaml
- gradle.properties
Set up GitHub CI for testing and building the app. No signing or publishing configs for now, only builds and stores the (unsigned) APKs as artifacts.
> Add workflow config for GitHub CI

- .github/dependabot.yml
- .github/workflows/app-test.yaml
As mentioned on Matrix, `actions/setup-java` got updated to v2 and has possible breaking changes by defaulting to AzulJDK.
So this PR updates it to v2 while maintaining the previous behavior (by using AdoptOpenJDK).
* update actions/setup-java to v2
* add dependabot for github-actions dependencies
* n/a
> ci(update-action): update actions/setup-java to v2

- app/build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- gradle.properties
- Remove now unnecessary jvmTarget from buildscript
- Update Room to 2.3.0 since earlier versions cause build errors with the new Kotlin release
> Update Kotlin to 1.5.0

- app/src/main/java/org/jellyfin/mobile/fragment/ConnectFragment.kt
The SDK can sometimes give false positives.
Partial fix for #366
> Treat recommended server without system info as unable to connect

- app/build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
Although the library already used desugaring it appears that it doesn't matter unless it is added to the app using it. We'll need to update the SDK's README later for that.
This fixes #373 and allows java.time to be used again.
> Add desugaring to support java.time

- app/src/main/assets/native/ExternalPlayerPlugin.js
- app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
- app/src/main/java/org/jellyfin/mobile/player/PlayerException.kt
- app/src/main/java/org/jellyfin/mobile/player/PlayerFragment.kt
- app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
- app/src/main/java/org/jellyfin/mobile/player/source/MediaQueueManager.kt
- app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceResolver.kt
- app/src/main/res/values/strings.xml
> Fix various playback crashes

- .github/workflows/gradlew-update.yaml
- .github/workflows/merge-conflict-labeler.yaml
``GH_TOKEN`` seems to be used internally by GitHub and it's making some actions we're using in some repos fail ([Source](https://github.com/alex-page/github-project-automation-plus/issues/39))
*(PRs made from users of the org are always successful, but PRs that aren't don't work, like Dependabot PRs. This can be checked by looking at the history of server repos and Jellyfin Vue)*
The org-wide secret should be renamed to something else to avoid confusion and further replacements or messes in GH's side. This PR replaces ``GH_TOKEN`` with ``JF_BOT_TOKEN``, which should be pretty generic.
> Replace GH_TOKEN with JF_BOT_TOKEN

- app/src/main/java/org/jellyfin/mobile/AppPreferences.kt
- app/src/main/java/org/jellyfin/mobile/MainActivity.kt
- app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/java/org/jellyfin/mobile/utils/WebViewUtils.kt
- app/src/main/res/values/strings.xml
Fixes #383
Adds an additional button to open the webview settings, it allows changing the used webview more easily. User needs to manually open the app again after changing it.
For the second alert (outdated webview) pressing on the background will cancel the dialog and never show it again. Adding an additional button was too much work because I'd need to make my own layout for it.
_note: this one actually says "open settings" instead of "settings" but I was too lazy to re-capture_
> Extended webview checks

- .github/workflows/app-publish.yaml
With the deployment/release of the Android app we ran into a few issues with the new GitHub actions based workflow, most of which got already fixed but apparently I messed up the `rsync`options in my initial PR :man_facepalming:.
This PR aims to fix that and hopefully get the workflow 100% operational for the next release.
* remove obsolete/release breaking `rsync` options
* n/a?
> fix incorrect rsync options

- app/src/main/java/org/jellyfin/mobile/player/source/Result.kt
suspending functions returning inline/value classes cause a crash in the coroutines library. When replacing the `kotlin.util.Result` class with a primitive custom alternative that isn't a value class, this crash doesn't happen anymore.
Fixes #397.
> Workaround for coroutines crash

- .github/workflows/app-build.yaml
- .github/workflows/app-publish.yaml
Observed with the latest release, the `version.txt` failed to be picked up during deploy.
This PR should fix that alongside simplify the folder structure used to hold the build artifacts.
Note: I omitted changing the `upload-assets` action for now until I or someone else has experience with a better alternative action.
* change the artifact directory structure of the build and deploy workflow
* n/a
> change directory structure of workflow artifacts

- app/src/main/java/org/jellyfin/mobile/AppPreferences.kt
- app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
Reverts jellyfin/jellyfin-android#363
Native player is not ready for wide use yet so we're setting the default back to web.
> Revert "Make ExoPlayer the default video player implementation"

- app/src/main/java/org/jellyfin/mobile/controller/ApiController.kt
- app/src/main/java/org/jellyfin/mobile/media/MediaService.kt
- app/src/main/java/org/jellyfin/mobile/media/car/LibraryBrowser.kt
- app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
- app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceResolver.kt
- buildSrc/src/main/kotlin/Dependencies.kt
- Bump SDK to beta 8
- Remove ApiController.currentUser in favor of ApiClient.userId
- Remove ApiController.requireUser in favor of ApiClient.userId
- Remove ApiController.currentDeviceId in favor of ApiClient.deviceInfo.id
- Remove explicit userId parameter when not required (replaced with SDK autofill)
> Update to SDK beta 8

- app/build.gradle.kts
- build.gradle.kts
- buildSrc/src/main/kotlin/Dependencies.kt
- gradle.properties
This should help with preparing for next server releases, next sdk releases or sdk development.
> Add option to switch between versions of the SDK

- app/src/main/assets/native/nativeshell.js
Since NativeShell is defined, the feature must be added manually.
https://github.com/jellyfin/jellyfin-web/blob/5c09077a2f12ae44e7b7d356ea8d9f35862b0b60/src/components/apphost.js#L336-L342
https://github.com/jellyfin/jellyfin-web/blob/5c09077a2f12ae44e7b7d356ea8d9f35862b0b60/src/components/apphost.js#L258-L260
Closes #421
> Enable subtitle burn settings for web player

- app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
Complement of #442
I think I found an error in your library @Maxr1998, or I am using it incorrectly?
```
D/SettingsFragment: appPreferences.exoPlayerAllowSwipeGestures = true
D/SettingsFragment: swipeGesturesPreference.checked = false
D/SettingsFragment: swipeGesturesPreference.getBoolean(false) = false
```
Could you check why it returns different values?
> Follow state changes for brightness & gesture preference

- app/src/main/java/org/jellyfin/mobile/MainActivity.kt
- app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
- app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt
- app/src/main/java/org/jellyfin/mobile/utils/SystemUtils.kt
- app/src/main/java/org/jellyfin/mobile/utils/UIExtensions.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_webview.xml
- Move CoordinatorLayout to WebViewFragment, since it's only supposed to be used there anyways
- Fade in WebView once the app has connected to the sever
- Fix a potential NPE when setting the locale
The background icon as discussed in #436 is still missing, but this should be easy to add now. I will play with that tomorrow.
cc: @CarlosOlivo
> Restructure Webapp UI

- .github/workflows/app-publish.yaml
This PR aims to fix our issues with the F-Droid build and our APKs signed via Gradle and not `apksigner` by reverting to using `apksigner`.
Big THANK YOU to @CarlosOlivo figuring this one out!
* change apk signing from gradle to apksigner
* should fix #414
> Sign APKs with apksigner instead of via Gradle

- .github/workflows/app-publish.yaml
what it says on the tin
* fix odd release naming due to signing
* change to assemble both debug and release builds in publish workflow
* add unsigned and debug builds to publish pack
* n/a?
> fix odd release naming due to signing

- app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
This makes sure the SDK and webui use an identical name. Requires SDK 1.0.1 to function properly.
> Use AuthorizationHeaderBuilder to encode device name send to web client

- buildSrc/src/main/kotlin/Dependencies.kt
Fixes an issue with special characters in device names
**Changes**
- Update jellyfin-sdk-kotlin to 1.0.1 to an issue with special characters in device names
**Issues**
> Update jellyfin-sdk-kotlin to 1.0.1

- app/src/main/java/org/jellyfin/mobile/MainActivity.kt
Speculative fix for now, but I think that's the cause for the crash with fragment manager not being able to apply the action after saving state.
> Fix a rare crash when starting the app

- app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt
- app/src/main/java/org/jellyfin/mobile/player/source/MediaQueueManager.kt
- app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceResolver.kt
- app/src/main/res/values/strings.xml
Fixes #499. Note that streams will always transcode at the moment, that bug seems to be on the server's end.
Please rebase after review.
> Fix LiveTV

- app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceResolver.kt
Previously the media source resolver did not check whether a media source required opening. Now, the media resolver appropriately opens the live stream for a media source, when required.
Even after the recent changes in fc05f2a5f104757438c77a861b098abc4da87fb0, the app still wouldn't open LiveTV for me using a HDHR Connect Duo. I took a peek at the web client, and realized that the app wasn't checking to see whether the media source had the requiresOpening flag set. Adding the code from my PR seems to resolve things for me.
_Note: my expertise is C and not Kotlin, so let me know if you have any feedback/recommendations. I'm not as fluent with the functional languages._
> Properly open live streams before playback if necessary

- app/src/main/java/org/jellyfin/mobile/api/DeviceProfileBuilder.kt
See https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/audio/ResamplingAudioProcessor.java
Codec strings according to https://trac.ffmpeg.org/wiki/audio%20types
> Force enable linear PCM codecs

- app/build.gradle.kts
- app/src/main/java/org/jellyfin/mobile/api/DeviceProfileBuilder.kt
- app/src/main/java/org/jellyfin/mobile/player/PlayerFragment.kt
- app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
- app/src/main/java/org/jellyfin/mobile/player/source/MediaQueueManager.kt
- app/src/main/java/org/jellyfin/mobile/utils/MediaExtensions.kt
- app/src/main/java/org/jellyfin/mobile/utils/TrackSelectionUtils.kt
- build.gradle.kts
- buildSrc/src/main/kotlin/Jellyfin.kt
- gradle/libs.versions.toml
- *A lot* of improvements related to #28. Adds support for multiple requested audio codecs like AC-3, E-AC-3, DTS, …
- Fix a bug where initial audio/subtitle track selections would be re-applied on ExoPlayer state changes.
- Refactor ExoPlayer event logging, current mapped track selections are logged on every manual audio/subtitle track change.
- Generally refactor track selection to be less complicated, more robust and easier to understand and debug.
> Add ffmpeg extension

- app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
Block Service Worker from caching that causes script injections to fail resulting in black screen or unable to connect on subsequent app restarts. 
Fixes #494
> Workaround for serviceWorker cache prevent injections

- app/src/main/java/org/jellyfin/mobile/api/ApiModule.kt
- app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
- app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
- app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSource.kt
- app/src/main/java/org/jellyfin/mobile/player/source/MediaQueueManager.kt
- app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceResolver.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- Changed `PLAYER_TIME_UPDATE_RATE` from 1 second to 10 seconds
Too much spam before, to the level of slowing down the server (at least in my case), also is the default in [jellyfin-web](https://github.com/jellyfin/jellyfin-web/blob/0dde17fbd7b8318269de53784543cb2981715dce/src/components/playback/playbackmanager.js#L2751-L2755) 
- Stop active encoding if transcoding when playbacks ends
---
Originally 2 sessions are created because jellyfin-web creates a [singleton](https://github.com/jellyfin/jellyfin-web/blob/2edf4661d5b19dcc59414ba3c157f2ff1ca71713/src/components/ServerConnections.js#L20-L39) per device (many users - one device), while jellyfin-sdk-kotlin proposes one user per [session](https://github.com/jellyfin/jellyfin-sdk-kotlin/blob/a1d7596c4ef3bf3cb69eaab9b7872d3b0e5d350a/jellyfin …
> Improve session integration

- app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
- app/src/main/java/org/jellyfin/mobile/player/source/MediaQueueManager.kt
Necessary to support e.g. AAC-LTP on some devices, without unnecessarily impacting battery life for codecs supported by the hardware.
> Fallback to prefer extension renderers if decoder fails

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/jellyfin/mobile/utils/PermissionRequestHelper.kt
- build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
- settings.gradle.kts
- Update Android Gradle to 7.0.3
- Move all plugin configuration to version catalog
- Move Kotlin version to version catalog
- Switch from KAPT to KSP
- Should improve build times since KSP doesn't do java stuff
- Also hopefully fixes the occasional "cache is corrupt manually delete build dir to fix" issue
- Update Room to 2.4.0 beta - required for KSP 1.0.0 compatibility
- Use Android 12 when compiling
- Also use it as target
- Added `exported=true` in manifest for mainactivity (required by android 12)
I wanted to move the "all projects repositories" from build.gradle.kts to settings.gradle.kts using dependencyResolutionManagement but that wasn't possible because it uses buildsrc constants for the SDK stuff. So I didn't move that part, otherwise the root build.gradle.kts could become …
> Build script refactoring

- app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
Without the `analyticsCollector` installed, any call using it would crash with a NPE. Thus, we enable it on release builds as well since the overhead should be minimal and the debugging information can be useful when users share their logs with us.
> Fix ExoPlayer crashing on track selection

- gradle/libs.versions.toml
Fixes #573. Will be released as 2.4.2 when confirmed working.
> Update Google Play Services to 20.1.0 to crash when using Chromecast on Android 12

- app/src/main/assets/native/ExoPlayerPlugin.js
- app/src/main/assets/native/ExternalPlayerPlugin.js
Previously, since the web client thought the external player was transcoding, due to a stubbed device profile, it added the transcoding offset to the current time on playback stop, sending the wrong value to the server. Simply marking all content as direct-playable fixes this.
Additionally, some timestamp handling issues related to ticks vs milliseconds were fixed.
Fixes #565.
> Fix stop time in ExternalPlayer

- app/src/main/java/org/jellyfin/mobile/player/PlayerMediaSessionCallback.kt
- app/src/main/java/org/jellyfin/mobile/player/PlayerNotificationHelper.kt
- app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
in the player control UI, the previous button only skips to the previous
track if the current position is smaller than
`Constants.MAX_SKIP_TO_PREV_MS`. however, the previous button in the
notification does not respect the current playback progress. this is
inconsistent and confusing behaviour.
this patch makes the previous button in the notification behave the same
as the previous button in the player control UI.
this makes the behaviour more consistent and also now the same as many
other popular media players, such as VLC, Spotify, etc.
> Fix inconsistent behaviour of the previous button

- app/src/main/res/values/styles.xml
Fix #581
I used `@color/jellyfin_primary_dark`, which is also used for the status bar.
I didn't find a solution to use the themes background color or transparency, which would look a bit nicer.
Perhaps someone with a physical Android 10+ smartphone can confirm/deny if the navigation bar displays content that is behind it. On a emulated device with API v30 it stil looks like the second screenshot in the above issue (no transparency).
> Apply explicit navigation bar color on API v28 and below

- .github/workflows/repo-stale.yaml
This PR aims to add a GitHub Action workflow to monitor, label and close stale issues.
It uses the Jellyfin-Bot token to comment and close stale Issues.
> NOTE: It explicitly does not touch PRs
* add a basic GitHub action workflow to monitor, label, and close stale issues within this repository
* successor to the discontinued Stale-Bot config
> add stale issue check workflow

- .github/workflows/gradlew-update.yaml
- .github/workflows/gradlew-validate.yaml
- .github/workflows/repo-stale.yaml
**Changes**
- Add repository condition to stale workflow
- Now disabled for forks
- Change runs-on for gradle workflows (accidently used ubuntu-latest)
- Change cron schedule to trigger 30 minutes before the gradlew-update workflow
- If both workflows trigger GitHub notifications the gradle update notification will be on the top
**Issues**
> Add repository condition to stale workflow

- app/src/main/java/org/jellyfin/mobile/player/audio/car/LibraryBrowser.kt
Closes #302 (first suggestion only, other two are duplicates).
> Android Auto: Sort playlists by name and return more by default

- app/src/main/assets/native/ExternalPlayerPlugin.js
- app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
#566 marked all video as direct-playable in the external player profile stub, but the web client still thinks that the player is transcoding when there are subtitles since the player profile lacked the supported subtitle formats. Add the supported formats in the player profile. 
Fixes #565.
> Add subtitle profiles to external player profile

- app/src/main/java/org/jellyfin/mobile/player/queue/QueueManager.kt
User can specify a version of a video they want to play, but previously the native player does not play the specified version and plays the default version instead.  Use the specified version from `playOptions` if available, similar to how it is handled in external player mode. 
Fixes #585.
> Use specified video version in native player

- app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
- app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Android 13 supports themed app icons.
This changes adds a monochromatic icon to `ic_launcher` and `ic_launcher_round`.
---
- **Before**:
- **After**:
> Add adaptive monochrome icon.

- app/src/main/java/org/jellyfin/mobile/app/AppModule.kt
- app/src/main/java/org/jellyfin/mobile/app/AppPreferences.kt
- app/src/main/java/org/jellyfin/mobile/player/deviceprofile/DeviceProfileBuilder.kt
- app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/res/values/strings.xml
**Changes**
Add a check box in the client settings for ExoPlayer to enable direct play SSA/ASS subtitles without transcoding.
ExoPlayer only partially supports ass subtitles. While support for more features of ass is being worked on it currently only displays it as basic text. Because of that the Jellyfin Android app used to always transcode those subtitles when selected before starting playback. However some people may only have files with basic text in ass subtitles, not care about all the fancy styling or need to avoid transcoding because their server isn't that powerful. Therefore this PR adds the option to direct play ass subtitles.
**Issues**
https://github.com/jellyfin/jellyfin-android/issues/696
https://github.com/jellyfin/jellyfin/issues/7809
> Add ability to direct play ass with exoplayer

- app/src/main/assets/native/nativeshell.js
- app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
Jellyfin 10.9 will add a new function to the NativeShell: downloadFiles. This is the same as downloadFile but can request multiple files at once.
This PR adds a basic implementation for it, internally it splits the request. In the future we can use  a queue or something to download the files more efficiently.
**Changes**
- Implement downloadFiles in NativeShell
- Add NativeInterface.downloadFiles
- Remove NativeInterface.downloadFile
**Issues**
jellyfin-web pull request: https://github.com/jellyfin/jellyfin-web/pull/4016
> Implement downloadFiles in NativeShell

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
Setting the package in AndroidManifest.xml is deprecated.
> Set namespace in build.gradle.kts instead of Manifest

- .github/workflows/repo-milestone.yaml
Tested in Maxr1998/jellyfin-android#1.
> Auto-apply milestones

- app/src/main/java/org/jellyfin/mobile/player/ui/PlayerFragment.kt
- app/src/main/res/layout/exo_player_control_view.xml
- app/src/main/res/values/styles.xml
**Changes**
I have added the back button functionality to the integrated player. I have used a `Toolbar` to achieve this. I was thinking of just adding a simple button but at this point, I feel like I'm reimplementing the `Toolbar` so I just replaced the `TextView` with the `Toolbar`.
**Issues**
Closes #896 
**Before**
**After**
> Add back button in the integrated player

- app/src/main/java/org/jellyfin/mobile/app/AppPreferences.kt
- app/src/main/java/org/jellyfin/mobile/player/ui/PlayerFragment.kt
- app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/res/values/strings.xml
This change prevents the screen orientation from automatically changing on playback start in ExoPlayer.
The player now keeps the currently active screen orientation. When the device is rotated (with auto-rotate active), the player rotates accordingly. The player is also rotated when pressing the fullscreen button.
Only works in ExoPlayer, the web player still shows the old behaviour. I'm not sure where the corresponding code is for the web player.
Probably fixes #141
> don't automatically change orientation for landscape video

- app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/res/values/strings.xml
> Add link to Android subtitle settings in client settings

- app/src/proprietary/java/org/jellyfin/mobile/player/cast/ChromecastConnection.java
**Changes**
I actually ran into this issue when I reopened the app quickly. The app will crash when it tries to release the `MediaRouter` callbacks.
> fixed potential crash when user reopens the app quickly

- fastlane/metadata/android/en-US/changelogs/default.txt
**Changes**
- Add default changelog to fastlane
It's copied from the ATV repo (https://github.com/jellyfin/jellyfin-androidtv/blob/master/fastlane/metadata/android/en-US/changelogs/default.txt) with a small change for the name.
The changelog is shown by F-Droid like here https://f-droid.org/en/packages/org.jellyfin.androidtv/
**Issues**
> Add default changelog to fastlane

- app/src/main/java/org/jellyfin/mobile/player/TrackSelectionHelper.kt
- app/src/main/java/org/jellyfin/mobile/player/queue/QueueManager.kt
**Changes**
We previously didn't handle encoded subtitles, aka subtitles baked into the video stream. Now, we restart the playback when such a stream is selected or when switching away from one.
**Issues**
Fixes #1017.
> Fix subtitle selection for encoded subtitles

- .editorconfig
This was the default before, and has to be explicitly disabled since Android Studio 2022.2.
> Disable line breaks after multiline when entries

- gradle/libs.versions.toml
Because Renovate is at it's 10 PR limit
**Changes**
- Update Jellyfin SDK to 1.4.2
- Update Exoplayer to 2.18.6 (including our ffmpeg extension)
**Issues**
> Update Jellyfin SDK (1.4.2) and Exoplayer (2.18.6)

- app/src/main/java/org/jellyfin/mobile/player/interaction/PlayerNotificationAction.kt
- app/src/main/java/org/jellyfin/mobile/player/interaction/PlayerNotificationHelper.kt
**Please rebase-merge.**
Required for #1038.
> Improve notification handling

- app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
- app/src/main/java/org/jellyfin/mobile/player/TrackSelectionHelper.kt
- app/src/main/java/org/jellyfin/mobile/player/interaction/PlayerNotificationHelper.kt
- app/src/main/java/org/jellyfin/mobile/player/queue/QueueManager.kt
- app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSource.kt
- app/src/main/java/org/jellyfin/mobile/player/ui/PlayerFragment.kt
- app/src/main/java/org/jellyfin/mobile/player/ui/PlayerMenus.kt
Caching media sources in the queue was unnecessary and overly complex, and could cause issues if playback options changed in between (i.e. a new bitrate). Additionally, there was some duplication between the cached play options and the current media source, which caused more confusion and issues.
> Rewrite queue management and play options handling

- app/src/main/AndroidManifest.xml
See:
- https://developer.android.com/develop/ui/views/layout/webapps/managing-webview#safe-browsing
- https://chromium.googlesource.com/chromium/src.git/+/master/android_webview/browser/safe_browsing/README.md
**Changes**
Unfortunately Google is marking the Jellyfin instances of some users as phishing. This breaks the Android app. Fortunately we can disable this tracking service using the Android manifest.
**Issues**
https://github.com/jellyfin/jellyfin-web/issues/4076
> Disable Google Safe Browsing Service in webviews

- app/src/main/java/org/jellyfin/mobile/player/ui/PlayerMenus.kt
**Changes**
Because the menus use setGroupCheckable with exclusive=true, it isn't necessary to uncheck the other items. Furthermore, while transcoding, the media source is updated and the menu rebuilt (with the new selections already). This causes the clickedItem to become outdated/invalid in the fragment.onXTrackSelected callback. As a result, the selection will be invalidated. To fix this, we assume that selections are always successful and immediately apply the selection to the clicked item before notifying the fragment.
**Issues**
Fixes #1024.
> Fix player menu track selection

- app/src/main/java/org/jellyfin/mobile/player/deviceprofile/DeviceProfileBuilder.kt
ExoPlayer supports decoding embedded pgssub subtitles, so they should be enabled.
Tested locally and confirmed working.
I also removed the likely invalid `pgs` specification from the external player profile, since ffprobe lists pgs subtitles as `pgssub`.
> Add pgssub to ExoPlayer subtitle codecs

- app/src/main/assets/native/ExoPlayerPlugin.js
**Changes**
This resolves a problem where non-fullscreen media like theme videos would be played in ExoPlayer, instead of playing as a backdrop in the web interface.
**Issues**
Fixes #706.
> Only play fullscreen video in ExoPlayer

- app/src/main/java/org/jellyfin/mobile/player/ui/PlayerFragment.kt
- app/src/main/java/org/jellyfin/mobile/player/ui/PlayerFullscreenHelper.kt
- app/src/main/java/org/jellyfin/mobile/player/ui/PlayerMenus.kt
> Fix insets handling on Android 10 and below

- app/baselineWorkaround.gradle
- app/build.gradle.kts
- gradle/libs.versions.toml
**Changes**
- Add workaround for non reproducible baseline profiles in AGP to libre builds
- This workaround must be written in Groovy because it uses internal classes/functions which the Kotlin compiler guards against
Additional context: https://github.com/jellyfin/jellyfin-androidtv/pull/2558, https://github.com/jellyfin/jellyfin-androidtv/issues/1639
**Issues**
Fixes #414
> Add workaround for non reproducible baseline profiles in AGP to libre builds

- app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
- app/src/main/java/org/jellyfin/mobile/player/deviceprofile/DeviceProfileBuilder.kt
When the bitrate is set to null the app will be unable to find a media source to play. The max bitrate was removed by accident when bitrate selection was added to the internal player.
**Changes**
- Fix bitrate not set for external player profile
**Issues**
Fixes #1046
> Fix bitrate not set for external player profile

- app/src/main/assets/native/ExoPlayerPlugin.js
- app/src/main/assets/native/ExternalPlayerPlugin.js
Because neither player currently supports SyncPlay, detecting a running session and falling back to the web player makes a lot of sense.
> Disable ExoPlayer and External player while in SyncPlay

- app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
**Changes**
Due to security-related changes in Android 13, the entrypoint must be the default start activity.
This requires https://code.videolan.org/videolan/vlc-android/-/merge_requests/1738 to be merged and released for playback tracking to work again.
**Issues**
Fixes #912
> Fix VLC external player crashing on Android 13

- app/src/main/java/org/jellyfin/mobile/player/deviceprofile/DeviceProfileBuilder.kt
Add support for dvb_subtitles to ExoPlayer. Tested with Movistar IPTV streams.
> Add dvbsub to ExoPlayer subtitle codecs

- app/build.gradle.kts
- buildSrc/src/main/kotlin/VersionUtils.kt
- gradle/libs.versions.toml
Not necessary anymore after exclusively using renovate.
> Remove dependency updates plugin

- app/src/main/java/org/jellyfin/mobile/MainActivity.kt
- app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
- app/src/main/java/org/jellyfin/mobile/utils/BackPressInterceptor.kt
- app/src/main/java/org/jellyfin/mobile/webapp/WebViewFragment.kt
This removes usages of the deprecated onBackPress method and instead relies on the new onBackPressedDispatcher while providing compatibility with the way we stack Fragments on top of each other (see BackPressInterceptor.kt for a more detailed explanation).
> Introduce BackPressInterceptor

- app/src/main/java/org/jellyfin/mobile/player/ui/PlayerFragment.kt
When using ExoPlayer, this allows users to exit the full-screen mode by pressing the back button, similar to e.g. the YouTube app.
> Allow to exit from fullscreen with the back button in ExoPlayer

- app/src/main/java/org/jellyfin/mobile/MainActivity.kt
`repeatOnLifecycle(Lifecycle.State.STARTED)` caused the flow collection to be restarted after the activity was stopped and then started again (for example, when opening another activity on top and then going back). However, this triggered `handleServerState` with the current state again, which unintentionally replaced the current fragment (for example the player or settings) with the WebViewFragment. The solution is to permanently collect the latest server state, but delay its application to the lifecycle start of the activity.
> Fix app returning to WebViewFragment when activity restarts

- app/src/main/java/org/jellyfin/mobile/player/interaction/PlayerNotificationHelper.kt
> Fix integrated player crashing on Android 14

- app/src/main/assets/native/ExternalPlayerPlugin.js
- app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
- app/src/main/java/org/jellyfin/mobile/player/deviceprofile/DeviceProfileBuilder.kt
- app/src/main/java/org/jellyfin/mobile/player/interaction/PlayOptions.kt
- app/src/main/java/org/jellyfin/mobile/player/queue/QueueManager.kt
- app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceResolver.kt
Instead of using a device profile like for ExoPlayer, we always build the direct stream URL, and at the same time tweak the media source request so that it never suggests transcoding. We do that by supplying an effectively unlimited maximum bit rate, which was previously hard-coded to 120 Mbps through the device profile.
Fixes #970.
> Ensure ExternalPlayer always direct plays

- app/src/main/AndroidManifest.xml
**Changes**
To prevent USB or Bluetooth keyboards from restarting the app when connected/disconnected, we also need to handle the `navigation` configuration change.
**Issues**
Fixes #897.
> Prevent keyboard (dis)connection from restarting the app

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/jellyfin/mobile/MainActivity.kt
- app/src/main/java/org/jellyfin/mobile/app/AppPreferences.kt
- app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
- app/src/main/java/org/jellyfin/mobile/events/ActivityEvent.kt
- app/src/main/java/org/jellyfin/mobile/events/ActivityEventHandler.kt
- app/src/main/java/org/jellyfin/mobile/utils/BluetoothPermissionHelper.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/java/org/jellyfin/mobile/utils/PermissionRequestHelper.kt
- app/src/main/java/org/jellyfin/mobile/utils/SystemUtils.kt
- app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt
- app/src/main/res/values/strings.xml
**Changes**
Since Android S, a new permission is required to be able to receive the relevant broadcast events.
**Issues**
Fixes #1116.
> Fix bluetooth event handling

- README.md
**Changes**
- Updated README.md with release flavors
**Issues**
Fixes #1226
> Explain release flavors in README

- app/src/main/assets/native/ExternalPlayerPlugin.js
- app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
- app/src/main/java/org/jellyfin/mobile/player/deviceprofile/DeviceProfileBuilder.kt
**Changes**
To get external subtitle streams, we have to provide a device profile when resolving the media source.
**Issues**
Fixes #1258.
> :bug: Fix External Player missing external subtitles

- app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
- app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSource.kt
- app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceResolver.kt
**Changes**
This fix implements adding LiveStreamId to server calls from the Android client to stop LiveTV playback. This is an implementation of the recommended fix by @jellouser in issue #1279.
This change addresses the issue of the tuner not being released by the server when Live TV playback is stopped in the Anrdroid client.
**Issues**
Fixes #1279
> Fix Live TV playback stop not releasing tuner

- .github/workflows/app-publish.yaml
**Changes**
Fixes publishing
**Issues**
https://github.com/r0adkll/sign-android-release/issues/84
> Specify BUILD_TOOLS_VERSION for r0adkll/sign-android-release step in publish workflow

- app/src/main/java/org/jellyfin/mobile/player/interaction/PlayerNotificationHelper.kt
**Changes**
Adds a call to `setOngoing()` during the creation of the playback notification to determine if the notification can be dismissed. Ongoing notifications won't be dismissed by clicking 'clear all' in the system dropdown menu.
**Issues**
Fixes #1284
> Prevent notification from being dismissed while playback is active

- app/src/main/java/org/jellyfin/mobile/player/deviceprofile/DeviceProfileBuilder.kt
**Changes**
Adds VP9 codec support to the list of supported codecs in MP4 containers.
After testing across various players and environments, including ExoPlayer, VLC, and major web browsers, VP9 in MP4 containers seem to work reliably. This PR should ensure broader compatibility and aligns with real-world usage.
**Issues**
Fixes #1311
> Add support for VP9 in MP4 containers

- app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
- gradle/libs.versions.toml
Adds support for `singleChoice` preferences with an Int key.
> Update dependency de.maxr1998:modernandroidpreferences to v2.4.0-beta2

- app/src/main/java/org/jellyfin/mobile/utils/SystemUtils.kt
**Changes**
Adds a third option to the initial download method dialog, allowing users to properly pick between the three network options
**Issues**
Fixes #1330
> Fix initial download method dialog

- app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt
- app/src/main/res/values/strings.xml
**Changes**
Adds a section in the settings screen which gives users the option of changing their preferred download network. Previously, users were unable to allow or restrict mobile data downloads after making the initial choice. Additionally updates the message displayed when the initial dialog is displayed to inform users their choice can be updated.
**Issues**
Fixes #1326
> Allow changing download network preference

- app/src/main/java/org/jellyfin/mobile/webapp/JellyfinWebChromeClient.kt
- app/src/main/java/org/jellyfin/mobile/webapp/LoggingWebChromeClient.kt
- app/src/main/java/org/jellyfin/mobile/webapp/WebViewFragment.kt
**Changes**
This fix adds the invocation of the system file picker for `onShowFileChooser` in the WebChromeClient to enable the upload of local subtitle files.
It implements the recommendation of @Maxr1998 in issue #1082
**Issues**
Fixes #1082
> Fix system file browser not being invoked

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
- app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt
`RemotePlayerService` service was not being properly started as a foreground service for media playback, causing playback stoppage after every track (or sooner for some folks), on android 14.
Different vendors may be more or less aggressive with killing of non-foreground service etc, so people may have gotten different results from the same root issue.
**Changes**
- Changes the manifest entry for `RemotePlayerService` to include the `foregroundServiceType="mediaPlayback"` attribute (see ["Foreground service types are required"](https://developer.android.com/about/versions/14/behavior-changes-14#fgs-types))
- Declares the foreground service behavior as part of the notification (see same req)
- Uses `startForeground` instead of `notificationManager.notify`
- Uses …
> Fix background playback stopping on Android 14

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
**Changes**
Alter build to use binary-only distribution of the Gradle wrapper.
This saves nearly 100MB on download (138MB instead of 230MB) and more than that in disk space. The complete distribution of the wrapper offers no value to the majority of contributors.
**Issues**
> Switch to binary-only Gradle distribution

- app/build.gradle.kts
- build.gradle.kts
**Changes**
Fix these deprecations:
* https://kotlinlang.org/docs/whatsnew20.html#deprecated-old-ways-of-defining-compiler-options
* https://docs.gradle.org/current/userguide/upgrading_version_8.html#project_builddir
**Issues**
> Fix deprecations in build scripts

- app/src/main/java/org/jellyfin/mobile/player/deviceprofile/DeviceProfileBuilder.kt
**Changes**
Adds OPUS to the MP4 container direct play profile.  OPUS is supported for direct play in other containers, but not MP4.  The MP4 spec supports OPUS.
**Issues**
Resolves this user's issue with unnecessary transcoding.
https://forum.jellyfin.org/t-solved-direct-play-problem-with-mp4-and-certain-codecs-on-android-native-player
> Add opus to MP4 direct play profile

- app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
**Changes**
The playback setting "Play next episode automatically" is being ignored, next episodes are always played regardless of the setting state.
This PR adds a request to the user endpoint to check if the autoplay setting has been enabled.
If internal exoplayer is used, the autoplay preference is now being taken into account when an episode of a series ends.
**Issues**
Fixes:
#1470
#1420
#1384
> Fix episode autoplay preference having no effect

- app/src/main/java/org/jellyfin/mobile/player/interaction/PlayerNotificationHelper.kt
- app/src/main/res/values-v29/dimens.xml
**Changes**
Use MediaMetadata art to override large icon in notification, fix art not clear issue.
Before:
After:
> Fix the issue of blurry media images in notifications.

- app/build.gradle.kts
- gradle/libs.versions.toml
**Changes**
Migrate to the Room Gradle plugin introduced in Room 2.6.0.
> The plugin configures the project such that generated schemas (which are
> an output of the compile tasks and are consumed for auto-migrations) are
> correctly configured to have reproducible and cacheable builds.
https://developer.android.com/jetpack/androidx/releases/room#gradle-plugin
Running Gradle tasks such as `assembleDebug` twice in a row now leads to tasks in the second run being up to date, allowing incremental compilation to work correctly.
**Issues**
> Configure Room with Gradle plugin

- app/src/main/java/org/jellyfin/mobile/app/ApiClientController.kt
- app/src/main/java/org/jellyfin/mobile/app/AppModule.kt
- app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
- app/src/main/java/org/jellyfin/mobile/player/audio/MediaService.kt
- app/src/main/java/org/jellyfin/mobile/player/audio/car/LibraryBrowser.kt
- app/src/main/java/org/jellyfin/mobile/player/deviceprofile/DeviceProfileBuilder.kt
- app/src/main/java/org/jellyfin/mobile/player/queue/QueueManager.kt
- app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceResolver.kt
- gradle/libs.versions.toml
**Changes**
Updated SDK version and fixed build errors.
Also added the API authorization header to exoplayer since the access token is no longer passed via URL for Android Auto (see https://github.com/jellyfin/jellyfin-sdk-kotlin/pull/871).
I have tested the Android Auto functionality and it seems to work fine. The only thing I cannot test and suspect that may not work is casting. Not sure how I would add the header there since CastPlayer cannot use a DataSource.Factory. In https://github.com/google/ExoPlayer/issues/4760 they claim that the receiver app is responsible for authentication. Not sure if this is implemented in [jellyfin/jellyfin-chromecast](https://github.com/jellyfin/jellyfin-chromecast) though.
> Update jellyfin-sdk-kotlin to v1.6.1

- app/build.gradle.kts
Should not require any changes since it's only the compileSdk and not the targetSdk.
> Compile against SDK 35 (Android 15)

- app/src/main/java/org/jellyfin/mobile/player/ui/PlayerFragment.kt
**Changes**
This removes the overrides for the back gesture in the integrated player.
The original behaviour breaks native android gestures and makes it impossible to leave playback without using the X-button. This is highly irritating since it deviates from default-android behaviour.
**Issues**
Fixes #1212
> Remove back-interceptor to not break expected behavior

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/jellyfin/mobile/player/interaction/PlayerNotificationHelper.kt
- app/src/main/java/org/jellyfin/mobile/ui/content/ImageProvider.kt
- app/src/main/java/org/jellyfin/mobile/utils/MediaExtensions.kt
Instead of using the large icon property on the notification, we can pass an artwork uri into the media metadata of our media session. This uri can refer to a content provider in the app that loads the image from the server.
Follow-up to #1493.
> Load media session artwork from content provider

- app/src/main/java/org/jellyfin/mobile/downloads/JellyfinDownloadService.kt
This is just a very small addition to the download PR changing the progress from a global progress bar based on average downloaded, to an individual percentage per download item.
> Add individual progress in download notification

- app/src/main/java/org/jellyfin/mobile/webapp/JellyfinWebViewClient.kt
When the app opens it tries to load the web-ui from the server. In case that fails (e.g. server is offline or doesn't host the web-ui) it should go back to the connection screen and show an error.
Until now our behavior was a bit too aggressive, it would pop back for pretty much ALL network errors. This would cause issues for users using custom CSS with dead links (CSS import/background images etc) as the app would think those meant the app could not load the webview.
**Changes**
- Update the error handling to only close the webview if the error is triggered on the main frame (the webview page that we load) and not for secondary resources.
- Remove onErrorReceived call from onReceivedSslError as our cancelling of the handler will already propagate to the other error handlers
**Issues** …
> Fix webview closing on unimportant network errors

- app/src/main/assets/native/nativeshell.js
- app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
Related: jellyfin/jellyfin-web#6833
**Changes**
- Implement support for the new "downloadmanagement" app feature in the nativeshell. This will add a "downloads" link to the app menu so the user can access downloads when connected to a server.
- Sort features array in our JS file.
**Issues**
> Implement DownloadManagement app feature in nativeshell

- app/build.gradle.kts
- app/src/main/java/org/jellyfin/mobile/app/AppModule.kt
- app/src/main/java/org/jellyfin/mobile/data/entity/DownloadEntity.kt
- app/src/main/java/org/jellyfin/mobile/downloads/DownloadUtils.kt
- app/src/main/java/org/jellyfin/mobile/downloads/DownloadsAdapter.kt
- app/src/main/java/org/jellyfin/mobile/downloads/DownloadsFragment.kt
- app/src/main/java/org/jellyfin/mobile/player/interaction/PlayerNotificationHelper.kt
- app/src/main/java/org/jellyfin/mobile/ui/content/ImageProvider.kt
- app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt
- app/src/main/res/drawable/ic_local_movies_white_128.xml
- app/src/main/res/drawable/ic_local_movies_white_64.xml
- app/src/main/res/layout/download_item.xml
- app/src/main/res/layout/fragment_downloads.xml
- app/src/main/res/values/dimens.xml
- gradle/libs.versions.toml
Update coil dependency from 2.7.0 to 3.2.0
**Changes**
Use coil to display the download thumbnail with error handling.  This fixes issue with bitmap decoding being done in the RecyclerView adapter.
> Update coil dependency from 2.7.0 to 3.2.0

- app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
- app/src/main/java/org/jellyfin/mobile/bridge/NativePlayer.kt
- app/src/main/java/org/jellyfin/mobile/data/entity/DownloadEntity.kt
- app/src/main/java/org/jellyfin/mobile/downloads/DownloadsFragment.kt
- app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt
- app/src/main/java/org/jellyfin/mobile/player/interaction/PlayOptions.kt
- app/src/main/java/org/jellyfin/mobile/player/interaction/PlayerEvent.kt
- app/src/main/java/org/jellyfin/mobile/player/queue/QueueManager.kt
- app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSource.kt
- app/src/main/java/org/jellyfin/mobile/player/source/LocalJellyfinMediaSource.kt
- app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceResolver.kt
- app/src/main/java/org/jellyfin/mobile/player/ui/PlayState.kt
- app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
- app/src/main/java/org/jellyfin/mobile/utils/MediaExtensions.kt
Updated all the spots where manual math was being used to convert to and from ticks, to use the built in time utilities instead
`ticks / Constants.TICKS_PER_MS` became `*.ticks.inWholeMilliseconds`
`ms * Constants.TICKS_PER_MS` became `*.milliseconds.inWholeTicks`
> Use kotlin time over manual math for tick conversions
