jellyfin/jellyfin-android

app/src/main/assets/www/native/apphost.js, app/src/main/assets/www/native/nativeshell.js, app/src/main/java/org/jellyfin/android/bridge/NativeInterface.kt
I tried to simply the NativeShell API a bit
=> Simplified NativeShell API

app/src/main/AndroidManifest.xml, app/src/main/java/org/jellyfin/mobile/WebappActivity.kt, app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt, app/src/main/java/org/jellyfin/mobile/player/PlayerActivity.kt, app/src/main/java/org/jellyfin/mobile/utils/SmartOrientationListener.kt
=> Improve orientation handling

app/src/main/java/org/jellyfin/mobile/WebappActivity.kt, app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt, app/src/main/java/org/jellyfin/mobile/utils/UIExtensions.kt, app/src/main/res/values-land-v28/styles.xml, app/src/main/res/values-v29/styles.xml, app/src/main/res/values/styles.xml
=> Fullscreen and styles tweaks, system gestures support

app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt, app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSource.kt, app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceManager.kt, app/src/main/java/org/jellyfin/mobile/utils/MediaExtensions.kt, app/src/main/res/values/strings.xml
Parse URI in MediaSource, extract media id, show play method in playback info, refactor intent handling
=> MediaSource tweaks

buildSrc/src/main/kotlin/VersionUtils.kt
Don't look at the branch name...
=> Fix version name not removing "v" prefix

app/src/main/AndroidManifest.xml, app/src/main/java/org/jellyfin/mobile/MainActivity.kt, app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt, app/src/main/java/org/jellyfin/mobile/bridge/NativePlayer.kt, app/src/main/java/org/jellyfin/mobile/utils/SystemUtils.kt, app/src/main/java/org/jellyfin/mobile/webapp/ConnectionHelper.kt, app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt
This should fix #66 but I can't test it locally because of a signature mismatch causing Android Studio to just remove the old app.
=> Rename WebappActivity to MainActivity

app/build.gradle.kts, app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt, app/src/main/java/org/jellyfin/mobile/utils/Constants.kt, buildSrc/src/main/kotlin/Dependencies.kt
This is for now the most basic use of the apiclient, I'm already working on using it for more things such as server connecting and progress submission, but that still needs some planning regarding architecture and design.
=> Add apiclient dependency, resolve device info via apiclient

app/src/main/java/org/jellyfin/mobile/ApplicationModule.kt, app/src/main/java/org/jellyfin/mobile/MainActivity.kt, app/src/main/java/org/jellyfin/mobile/api/TimberLogger.kt, app/src/main/java/org/jellyfin/mobile/utils/Constants.kt, app/src/main/java/org/jellyfin/mobile/utils/JSONExtensions.kt, app/src/main/java/org/jellyfin/mobile/webapp/ConnectionHelper.kt, app/src/test/java/org/jellyfin/mobile/HelperTests.kt
Integrates the Java API client into the app, pulling login credentials from the webapp. Currently unused, but will replace some direct communication with the webapp in the future.
=> API client integration

app/src/main/assets/native/externalplayer.js, app/src/main/assets/native/nativeshell.js, app/src/main/java/org/jellyfin/mobile/AppPreferences.kt, app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt, app/src/main/java/org/jellyfin/mobile/bridge/NativePlayer.kt, app/src/main/java/org/jellyfin/mobile/settings/SettingsActivity.kt, app/src/main/java/org/jellyfin/mobile/settings/VideoPlayerType.java, app/src/main/java/org/jellyfin/mobile/utils/Constants.kt, app/src/main/res/values/strings.xml, buildSrc/src/main/kotlin/Dependencies.kt
Allow to switch between web player, ExoPlayer and external player via client settings
=> Rework player implementation setting

app/src/main/assets/native/externalplayer.js, app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
Some changes in external player
1. Fixes in time tracking which resets last playback position to zero when there was no valid external player selection and / or Activity / Thread is killed by Android System (EVENT_CANCELED)
2. Added a device profile that assumes all video and audio formats are supported on external players which allows to process the file / DirectStream as-is.
So even if the device does not report a compatible codec or the external player has SW codecs, it allows the playback. (like MX Player with Custom Codec [DTS, AC3, etc]
Side effect: Transcoding is officially no longer possible on external players. (Well, it never was supported from the beginning)
3. About the change in fun notifyEvent on ExternalPlayer.kt
This fix a very rare runtime exception that happens when …
=> External player changes

app/src/main/java/org/jellyfin/mobile/player/PlayerActivity.kt
=> Fixed controller hiding when seeking in native player

buildSrc/src/main/kotlin/Dependencies.kt
=> Bump apiclient to version 0.7.5 to fix discovery issues.

buildSrc/src/main/kotlin/Dependencies.kt
See jellyfin/jellyfin-apiclient-java/pull/119 for some more info.
=> Update apiclient to fix issues with server discovery

app/src/main/res/values/strings.xml
Most people are aware about this but this kind of warning is present in all the apps I use, so I guess it doesn't hurt.
=> Add warning about using mobile data

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/org/jellyfin/mobile/ApplicationModule.kt, app/src/main/java/org/jellyfin/mobile/JellyfinApplication.kt, app/src/main/java/org/jellyfin/mobile/MainActivity.kt, app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt, app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt, app/src/main/java/org/jellyfin/mobile/bridge/NativePlayer.kt, app/src/main/java/org/jellyfin/mobile/fragment/ConnectFragment.kt, app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt, app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt, app/src/main/java/org/jellyfin/mobile/utils/Constants.kt, app/src/main/java/org/jellyfin/mobile/utils/LocaleUtils.kt, app/src/main/java/org/jellyfin/mobile/utils/PermissionRequestHelper.kt, app/src/main/java/org/jellyfin/mobile/utils/SystemUtils.kt, app/src/main/java/org/jellyfin/mobile/utils/UIExtensions.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/fragment_connect.xml, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/layout/fragment_webview.xml, buildSrc/src/main/kotlin/Dependencies.kt
Requires #165 to be merged first.
=> Use fragments to separate UI components

app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt
Works at least in MPV & MX Player
VLC Player not supported: https://trac.videolan.org/vlc/ticket/18736
=> Add support for external subtitles in some external players

app/build.gradle.kts, app/schemas/org.jellyfin.mobile.model.sql.JellyfinDatabase/1.json, app/src/main/java/org/jellyfin/mobile/ApplicationModule.kt, app/src/main/java/org/jellyfin/mobile/JellyfinApplication.kt, app/src/main/java/org/jellyfin/mobile/model/DatabaseModule.kt, app/src/main/java/org/jellyfin/mobile/model/sql/JellyfinDatabase.kt, app/src/main/java/org/jellyfin/mobile/model/sql/dao/ServerDao.kt, app/src/main/java/org/jellyfin/mobile/model/sql/dao/UserDao.kt, app/src/main/java/org/jellyfin/mobile/model/sql/entity/ServerEntity.kt, app/src/main/java/org/jellyfin/mobile/model/sql/entity/ServerUser.kt, app/src/main/java/org/jellyfin/mobile/model/sql/entity/UserEntity.kt, buildSrc/src/main/kotlin/Dependencies.kt
Required to persist server data at a later date, unused for now.
=> Initial database setup

app/src/main/java/org/jellyfin/mobile/fragment/ConnectFragment.kt, app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
This should (partially?) fix #172
=> Always trim ending slashes from URL in apiclient

app/src/main/assets/native/exoplayer.js, app/src/main/java/org/jellyfin/mobile/player/ExoPlayerCodec.kt, app/src/main/java/org/jellyfin/mobile/player/ExoPlayerFormats.kt, app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt, app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceManager.kt, buildSrc/src/main/kotlin/Dependencies.kt
This PR adds some optimizations to audio capabilities of the device. 
I added max channels and max sample rate to the device profile. 
I also added profiles for aac codec.
Also updated the version of exoplayer to 2.12.0
=> Audio device profile optimizations + exoplayer update

app/src/main/java/org/jellyfin/mobile/player/PlayerActivity.kt
This allows to zoom in on movies with e.g. a wide aspect ratio (21:9) that are embedded into a 16:9 frame, as phones nowadays often have taller screens (ultra-wide in landscape).
=> Add zoom feature to ExoPlayer

app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt, app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
Closes #149
Note: Release of mpv-android with https://github.com/mpv-android/mpv-android/commit/f70298fe23c4872ea04fe4f2a8b378b986460d98 not available yet.
=> Add playback tracking support for mpv-android external player

app/src/main/assets/native/externalplayer.js
Closes #192
Required for #177
Based on [MX Player Supported Subtitle Formats](https://mx.j2inter.com/features#h.p_ID_231:~:text=Supported%20Subtitle%20Formats)
=> Add support for more external subtitle formats in some external players

app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
To try this add multiple slashes to the end of the server address, like `http://192.168.13.37:8096//`
=> Fix 404 when loading server

app/src/main/java/org/jellyfin/mobile/fragment/ConnectFragment.kt, app/src/main/java/org/jellyfin/mobile/utils/ApiExtensions.kt, app/src/main/res/values/strings.xml
Added logging to hopefully help debug connectivity issues. Also makes the version check a bit more strict and requires 10.6.0 >=
=> Improved connect logging

README.md
=> Update to trigger a commit hash change

app/src/main/assets/native/nativeshell.js, app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
Fixes server selection in 10.7 >=
=> Add selectServer function to native shell

.ci/azure-pipelines.yml
Moves the "jellyfin" variable group to the publish task.
Fixes a regression in #225
=> Fix publishing

app/build.gradle.kts, app/src/libre/java/org/jellyfin/mobile/cast/CastPlayerProvider.kt, app/src/main/java/org/jellyfin/mobile/cast/ICastPlayerProvider.kt, app/src/main/java/org/jellyfin/mobile/media/MediaService.kt, app/src/proprietary/java/org/jellyfin/mobile/cast/CastPlayerProvider.kt
=> Include cast extension in proprietary flavor only

.ci/azure-pipelines.yml, app/build.gradle.kts
Used in fdroid to detect new releases
Closes #239
=> Create version.txt in pipeline

app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt
=> Fix background color in web player

app/src/main/AndroidManifest.xml, app/src/main/java/org/jellyfin/mobile/AppPreferences.kt, app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt, app/src/main/java/org/jellyfin/mobile/utils/Constants.kt, app/src/main/java/org/jellyfin/mobile/utils/SystemUtils.kt, app/src/main/res/values/strings.xml
Also allow Jellyfin to be installed/moved to external storage
Closes #264
=> Add download location option in client settings

app/src/main/java/org/jellyfin/mobile/player/PlayerFragment.kt, app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceManager.kt
Fixes some rare crashes in edge-cases and improves code readability.
=> Various crash fixes and improvements

app/src/libre/java/org/jellyfin/mobile/cast/CastPlayerProvider.kt, app/src/main/java/org/jellyfin/mobile/cast/ICastPlayerProvider.kt, app/src/main/java/org/jellyfin/mobile/media/MediaService.kt, app/src/proprietary/java/org/jellyfin/mobile/cast/CastPlayerProvider.kt, app/src/proprietary/java/org/jellyfin/mobile/cast/Chromecast.java
=> Fix Chromecast integration crashing the app without Play Services

gradle/wrapper/gradle-wrapper.properties
Saw the [f-droid bot](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7682) complain about it and the fix was trivial.
=> Add distributionSha256Sum to prevent MITM attacks.

README.md
- Added Google Play link
- Added Amazon Appstore link
- Added F-Droid link
- Removed discourse link (forum) - didnt' work for a while now
Depends on jellyfin/jellyfin-blog/pull/91 for the F-Droid image.
=> Add store links to readme

app/build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt, buildSrc/src/main/kotlin/VersionUtils.kt
=> Dependency maintanance

app/src/main/java/org/jellyfin/mobile/media/MediaService.kt, app/src/main/java/org/jellyfin/mobile/media/car/LibraryBrowser.kt, buildSrc/src/main/kotlin/Dependencies.kt, gradle.properties
=> Dependency updates

app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt, app/src/main/res/values/strings.xml
=> Client settings layout and wording tweaks

.github/workflows/merge-conflict-labeler.yaml
jellyfin/jellyfin-sdk-kotlin#235
=> Use eps1lon/actions-label-merge-conflict

app/src/main/java/org/jellyfin/mobile/JellyfinApplication.kt
=> Fix app crashing when webview is missing

app/src/main/java/org/jellyfin/mobile/fragment/ConnectFragment.kt, app/src/main/res/layout/fragment_connect.xml
Added loading indicator while connecting to host
=> Rework connection layout and show loading indicator while connecting to server

.github/workflows/app-build.yaml, .github/workflows/app-publish.yaml
=> Add gradle cache to app-build workflow

build.gradle.kts, buildSrc/src/main/kotlin/Dependencies.kt
**Changes**
- Update SDK snapshot version to master-SNAPSHOT
- See jellyfin/jellyfin-sdk-kotlin#264
**Issues**
=> Update SDK snapshot version to master-SNAPSHOT

app/src/main/java/org/jellyfin/mobile/media/MediaService.kt, app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt, app/src/main/java/org/jellyfin/mobile/utils/MediaExtensions.kt, buildSrc/src/main/kotlin/Dependencies.kt
=> Update ExoPlayer to 2.14

README.md
Moved to a separate Weblate project so had to update the links
=> Update weblate links

app/src/main/java/org/jellyfin/mobile/player/PlayerFragment.kt, app/src/main/java/org/jellyfin/mobile/utils/Constants.kt
=> Fix PiP crash on aspect ratios unsupported by Android

app/src/main/java/org/jellyfin/mobile/player/PlaybackMenus.kt, app/src/main/java/org/jellyfin/mobile/player/PlayerFragment.kt, app/src/main/java/org/jellyfin/mobile/player/PlayerGestureHelper.kt, app/src/main/java/org/jellyfin/mobile/player/PlayerLockScreenHelper.kt, app/src/main/java/org/jellyfin/mobile/utils/UIExtensions.kt
Cleans up the PlayerFragment quite a bit by extracting some functionality into separate classes.
Also adds PiP source hints for cleaner PiP transitions.
=> Player refactor

app/src/main/java/org/jellyfin/mobile/AppPreferences.kt, app/src/main/java/org/jellyfin/mobile/player/PlayerGestureHelper.kt, app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt, app/src/main/java/org/jellyfin/mobile/utils/Constants.kt, app/src/main/res/values/strings.xml
=> Remember brightness changes on ExoPlayer

.github/workflows/app-publish.yaml
=> Append -release to release APKs

app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt, app/src/main/java/org/jellyfin/mobile/utils/WebViewUtils.kt
See https://github.com/jellyfin/jellyfin-android/issues/453#issuecomment-873984436
Closes #453
Closes #456
=> Fix module script injection

app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSource.kt
Fallback to filename if not found
Closes #455
=> Use media item name as title when available

app/src/main/java/org/jellyfin/mobile/media/car/LibraryBrowser.kt, buildSrc/src/main/kotlin/Dependencies.kt
=> Update SDK to 1.0.0 release

app/src/main/java/org/jellyfin/mobile/settings/SettingsFragment.kt, app/src/main/res/values/strings.xml
Also renamed the string id to invalidate the translations.
=> Rename native player to integrated player

gradle/libs.versions.toml
=> Update jellyfin-sdk-kotlin to 1.0.2

app/src/main/java/org/jellyfin/mobile/fragment/WebViewFragment.kt
=> WebView error handling tweaks

app/src/main/java/org/jellyfin/mobile/api/DeviceProfileBuilder.kt, app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt, app/src/main/java/org/jellyfin/mobile/utils/SystemUtils.kt
Also adds some missing codec strings from the ffmpeg extension to supported containers.
Rebase please.
=> Fix and tweak mpegts and transcoding profiles

.github/workflows/app-build.yaml, .github/workflows/app-lint.yaml, .github/workflows/app-test.yaml
Copied from Jellyfin Kotlin SDK.
=> Lint workflow

README.md
See https://github.com/jellyfin/jellyfin-android/commit/930074737e1ac33f48d8232624b834f731b1f502#commitcomment-57425310
=> Fix wrong Weblate link in README

app/src/main/java/org/jellyfin/mobile/media/MediaService.kt, app/src/main/java/org/jellyfin/mobile/player/PlayerNotificationHelper.kt, app/src/main/java/org/jellyfin/mobile/utils/Constants.kt, app/src/main/java/org/jellyfin/mobile/webapp/RemotePlayerService.kt
PendingIntents have to be immutable since Android 12
=> Fix PendingIntent crash on Android 12

gradle/libs.versions.toml
=> Update ExoPlayer to 2.16.1

app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt, gradle/libs.versions.toml
Fixes an crash when using display preferences
=> Update SDK to 1.1.2

app/build.gradle.kts, app/src/main/java/org/jellyfin/mobile/ApplicationModule.kt, app/src/main/java/org/jellyfin/mobile/MainActivity.kt, app/src/main/java/org/jellyfin/mobile/fragment/ConnectFragment.kt, app/src/main/java/org/jellyfin/mobile/player/PlayerFragment.kt, app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt, app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceResolver.kt, app/src/main/java/org/jellyfin/mobile/utils/MediaExtensions.kt, app/src/main/java/org/jellyfin/mobile/utils/TrackSelectionUtils.kt, gradle/libs.versions.toml
Normal merge or rebase please :wink:
=> Update dependencies and fix some warnings

app/src/main/AndroidManifest.xml
=> Fix cast broken due to invalid manifest entry

gradle/libs.versions.toml
=> Update Jellyfin Kotlin SDK to 1.2.0

app/build.gradle.kts
=> Bump Android compile and target SDK to 32 (Android 12L)

app/build.gradle.kts, app/src/main/java/org/jellyfin/mobile/player/ui/PlayerGestureHelper.kt
I think this should be enough for the moment to merge #780.
=> Raise compileSdk to 33

.github/workflows/app-build.yaml, .github/workflows/app-lint.yaml, .github/workflows/app-publish.yaml, .github/workflows/app-test.yaml, .github/workflows/gradlew-update.yaml, .github/workflows/gradlew-validate.yaml, .github/workflows/repo-merge-conflict.yaml, .github/workflows/repo-stale.yaml
**Changes**
- Use Ubuntu 22.04
- Use Java 17
- Use Java Temurin distribution
- Use official Gradle setup action
- Use consistent naming scheme
- Use organization check instead of repository check
**Issues**
=> Update GitHub actions workflows

app/src/main/java/org/jellyfin/mobile/webapp/WebViewFragment.kt, app/src/main/res/layout/fragment_webview.xml, app/src/main/res/values/strings.xml
=> Add button to cancel loading before timeout

app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSource.kt, app/src/main/java/org/jellyfin/mobile/player/source/MediaSourceResolver.kt, app/src/main/java/org/jellyfin/mobile/player/ui/PlayerMenus.kt
=> Fix items not getting checked in bitrate selection popup

app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt, app/src/main/java/org/jellyfin/mobile/player/PlayerViewModel.kt, app/src/main/java/org/jellyfin/mobile/player/TrackSelectionHelper.kt, app/src/main/java/org/jellyfin/mobile/player/queue/QueueManager.kt, app/src/main/java/org/jellyfin/mobile/player/source/ExternalSubtitleStream.kt, app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSource.kt, app/src/main/java/org/jellyfin/mobile/player/ui/PlayerFragment.kt, app/src/main/java/org/jellyfin/mobile/player/ui/PlayerMenus.kt, app/src/main/java/org/jellyfin/mobile/utils/TrackSelectionUtils.kt
Add proper support for external audio streams, rework audio and subtitle selection, and support extracted subtitles during transcoding playback.
Also extracts some code to a new TrackSelectionHelper class.
=> Rework track handling and selection

app/src/main/java/org/jellyfin/mobile/player/TrackSelectionHelper.kt
=> Fix audio track selection for >= 10 tracks

app/src/proprietary/java/org/jellyfin/mobile/player/cast/ChromecastSession.java
**Changes**
Call the success callback  when result was successful.
To be honest this is so obvious that I am not sure if I am not missing something. I am still having issues with casting but this should be a step in the right direction.
**Issues**
Possibly related: https://github.com/jellyfin/jellyfin-android/issues/1029
=> Chromecast: call success callback when result was successful

.github/workflows/app-publish.yaml
**Changes**
Updates the secrets and locations to match other projects going forward.
**Issues**
N/A
=> Update CI to new repository secrets and layout

app/src/main/assets/native/nativeshell.js
**Changes**
Remove SubtitleProfiles override in `nativeshell.js`
**Issues**
Fix #1464
=> Fix subtitle burn settings for web player

.gitignore
**Changes**
Kotlin 2 creates files in `.kotlin` directory. These should be ignored by git.
https://kotlinlang.org/docs/whatsnew20.html#new-directory-for-kotlin-data-in-gradle-projects
**Issues**
=> Add .kotlin directory to gitignore

app/src/main/java/org/jellyfin/mobile/MainActivity.kt, app/src/main/java/org/jellyfin/mobile/player/ui/PlayerFragment.kt, app/src/main/java/org/jellyfin/mobile/player/ui/PlayerFullscreenHelper.kt, app/src/main/java/org/jellyfin/mobile/utils/UIExtensions.kt, app/src/main/java/org/jellyfin/mobile/webapp/WebViewFragment.kt
Fixes various issues with fullscreen and inset handling. Tested locally. Should preferably be rebase-merged.
=> Tweak fullscreen and insets handling for native player

app/src/main/assets/native/nativeshell.js
Guess who re-sorted some stuff and didn't look at the commas in #1627.
**Changes**
- Fix syntax error in native shell JavaScript
**Issues**
=> Fix syntax error in native shell JavaScript

app/build.gradle.kts, app/src/main/java/org/jellyfin/mobile/app/AppModule.kt, app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt, app/src/main/java/org/jellyfin/mobile/bridge/NativeInterface.kt, app/src/main/java/org/jellyfin/mobile/data/entity/DownloadEntity.kt, app/src/main/java/org/jellyfin/mobile/downloads/DownloadUtils.kt, app/src/main/java/org/jellyfin/mobile/events/ActivityEventHandler.kt, app/src/main/java/org/jellyfin/mobile/player/queue/QueueManager.kt, app/src/main/java/org/jellyfin/mobile/player/source/JellyfinMediaSourceSerializer.kt, app/src/main/java/org/jellyfin/mobile/ui/content/ImageProvider.kt, app/src/main/java/org/jellyfin/mobile/ui/screens/connect/ServerSelection.kt, build.gradle.kts, buildSrc/src/main/kotlin/VersionUtils.kt
Functionally this does not change anything.
**Changes**
- Fix various linter and compiler warnings
**Issues**
=> Fix various linter and compiler warnings

gradle/libs.versions.toml
Reverts jellyfin/jellyfin-android#1695
=> Revert "Update dependency com.google.devtools.ksp to v2.2.0-2.0.2"

gradle/libs.versions.toml
Reverts jellyfin/jellyfin-android#1688
=> Revert "Update Kotlin to v2.2.0"

app/build.gradle.kts
**Changes**
- Set archive name using the project.base extension instead of the setProperty function
**Issues**
=> Update app build script for Gradle 9 compatibility

app/build.gradle.kts
**Changes**
- Target Android 16 (API 36)
**Issues**
=> Target SDK 36 (Android 16)
