jellyfin/jellyfin-android

- .gitignore
- README.md
- hooks/after_prepare/uglify.js
- hooks/uglify-config.json
- package-lock.json
- package.json
Below is a summary of the changes made:
* Add package.json for dependencies
* Fix issues with new clean-css and uglify-js versions
* Update README.md to include build instructions
> Fix build issues

- new-file-header.txt
Add file header for new files. Refs https://github.com/jellyfin/jellyfin/pull/304
> Add new-file-header.txt

- hooks/after_prepare/uglify.js
- hooks/uglify-config.json
- package-lock.json
- package.json
This removes unused code in the uglify script that would compress images and removes `imagemin` as a dependency.
> Remove unused image minification

- platforms/android/.project
- platforms/android/res/values/strings.xml
- platforms/android/src/org/jellyfin/mobile/MainActivity.java
> Rebrand Emby to Jellyfin

- platforms/android/src/org/jellyfin/mobile/MainActivity.java
- src/cordova/apphost.js
- src/cordova/appshortcuts.js
- src/cordova/filerepository.js
- src/cordova/transfermanager.js
- src/cordova/wakeonlan.js
pulled from a branch made by @thornbill
> add stub files for missing native components

- gulpfile.js
- jellyfin-web.sh
- package-lock.json
- package.json
Moves the logic of modifying index.html to gulp instead of a shell script.
> Add gulp task to modify index.html

- src/cordova/apphost.js
> Temporarily disable AC3 support reporting to server

- gulpfile.js
Fixes config option I messed up when adding comment in https://github.com/jellyfin/jellyfin-android/commit/4bc4bbada4c03eb0e97df5c3581f7b1fafe50c8a#diff-b9e12334e9eafd8341a6107dd98510c9
Fixes https://github.com/jellyfin/jellyfin-android/issues/56
> Fix rebase option for clean-css

- docker-build.sh
Presents a nicer option with more flexibility rather than the hardcoded dev/master of the previous script.
> Improve build script handling of submodule

- Dockerfile
- build.sh
- docker-build.sh
Ensures that the upstream is fetched before checking out to avoid stale branches.
Fixes #26
> Improve build infrastructure

- config.xml
- package.json
- src/NativeShell/plugin.xml
I was seeing sporadic crashes and I think this might be the reason.
> Fix crash from outdated version of okhttp

- src/NativeShell/www/apphost.js
This PR addresses a small change for a bug that gives unexpected results when trying to play music files (at least).
> Fix bug fetching deviceProfile in apphost

- gulpfile.js
- package-lock.json
- package.json
Adds `uglify-es` for ES6 support in the gulp build
> Add support for ES6 in uglify task

- src/NativeShell/src/AppLogger.java
- src/NativeShell/src/LogbackLogger.java
- src/NativeShell/src/RemotePlayerService.java
Updates the apiclient namespace to match changes in jellyfin/jellyfin-apiclient-java#12
> Update apiclient namespace

- src/NativeShell/src/RemotePlayerService.java
I was having issues with #120 so we should remove it until it can be toggled from a submenu in the settings.
> Fix volume manager until it can be toggled

- build
Removes the conditional so the submodule is always initialized.
> Always initialize the submodule on build

- src/NativeShell/src/RemotePlayerService.java
> Simple fix to pause countdown with playback

- config.xml
- src/NativeShell/plugin.xml
- src/NativeShell/src/NativeShell.java
- src/NativeShell/src/RemotePlayerService.java
Automatically pause when Bluetooth is disconnected. Solves #161
> Fix #161: pause when BT disconnects

- config.xml
Release a new version with fixes from Cordova
> release a new version

- config.xml
- package-lock.json
- package.json
To take advantage of fixes in cordova-plugin-chromecast.
> Release new version

- config.xml
Updating the version code is required for Google Play to accept a new release.
> Update version for release

- gulpfile.js
- src/NativeShell/www/apphost.js
> Fix csp and progressive mkv for live tv playback

- package-lock.json
- package.json
Adds the Screen Orientation plugin to make `screen.orientation.lock` work.
Closes #241
> Add orientation plugin to support screen rotation

- config.xml
- package.json
> Update version for 0.9.9 release

- build-extras.gradle
- config.xml
- docker-build.sh
- hooks/copy-build-extras.js
- package-lock.json
This uses the same approach as https://github.com/jellyfin/jellyfin-androidtv/pull/407 to rename the built APKs to use the published filenames.
> Update output filename to published format

- src/NativeShell/src/build.gradle
**Changes**
- Pin the version of the apiclient to 0.6.0 (latest) so changes in the master branch won't break the builds
**Issues**
- None
> Pin the apiclient version to 0.6.0

- src/NativeShell/src/RemotePlayerService.java
- Supply duration metadata to mediaSession/notification
- Support media seek bar on Android 10 (and earlier custom ROMs that backported this) - however handling click events will require additional changes to jellyfin-web
- Make notification "ongoing" as long as the playback is running
- Show album name instead of when/chronometer progress on N and above (notification subText is shown in header since N)
- Remove unnecessary callback super calls
> Media notification improvements

- package.json
- src/NativeShell/src/RemotePlayerService.java
- yarn.lock
Compiled and tested this locally, everything seems to work just fine (~~nvm, notification is obviously broken. I'm gonna look into it I guess~~ - fixed).
> Bump jellyfin-web to 10.6.0

- src/cordova/exoplayer.js
> Exoplayer profile improvements
